

%%after loading .mat file generated by python, run this codes below:
figure
imagesc(abs(original));
set(gcf, 'Position', [00, 00, 350, 300])
set(gca,'FontSize', 10) % Font Size
colormap jet
colorbar
title('Laser Array Intensity Distribution')

phase = HelperClass.quantizePhase(angle(original));
figure
imagesc(phase);
set(gcf, 'Position', [00, 00, 350, 300])
set(gca,'FontSize', 10) % Font Size
colormap jet
colorbar
title('Laser Array Quantized Phase Distribution')

%% Then copy the quantized near field phase to python or matlab (below) to calculate the far field
nearField = abs(original).*(exp(1i*phase));
Angular_Spectrum = (fft2(fftshift(original))); %Near Field
figure
imagesc(abs(Angular_Spectrum).^2);
set(gcf, 'Position', [00, 00, 350, 300])
set(gca,'FontSize', 10) % Font Size
colormap jet
colorbar
title('Recovered Far Field Image')
