

%%after loading .mat file generated by python, run this codes below:
figure
imagesc(angle(original));
set(gcf, 'Position', [00, 00, 350, 300])
set(gca,'FontSize', 14) % Font Size
colormap jet
colorbar

phase = HelperClass.quantizePhase(angle(original));
figure
imagesc(phase);
set(gcf, 'Position', [00, 00, 350, 300])
set(gca,'FontSize', 14) % Font Size
colormap jet
colorbar

%% Then copy the quantized near field phase to python or matlab (below) to calculate the far field
nearField = original.*(exp(1i*phase));
Angular_Spectrum = fftshift(fft2(fftshift(nearField))); %Near Field
figure
imagesc(abs(Angular_Spectrum));
set(gcf, 'Position', [00, 00, 350, 300])
set(gca,'FontSize', 14) % Font Size
colormap jet
colorbar

